# Generated by Django 3.2.4 on 2021-06-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.CharField(max_length=5500),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.CharField(max_length=5000),
        ),
    ]
