# Generated by Django 3.2.4 on 2021-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20210624_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
