# Generated by Django 3.2.4 on 2021-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_auto_20210626_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bus_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
