# Generated by Django 3.2.4 on 2021-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_book_bus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.IntegerField(),
        ),
    ]
